getwd()
setwd("/Users/hu47936/Documents/HH Practice_R/Kaggle_Credit Card Prediction/")

# Reference Web
# https://www.r-bloggers.com/2015/09/how-to-perform-a-logistic-regression-in-r/
# https://www.kaggle.com/code/tanayatipre/credit-card-prediction-lr-rf-xgb-knn/notebook
# https://www.geeksforgeeks.org/logistic-regression-in-r-programming/
# https://stats.oarc.ucla.edu/r/dae/logit-regression/

library(tidyverse)
library(dplyr)
d.test<- read.csv("test_data.csv")
d.train<- read.csv("train_data.csv")

# Exploration
summary(d.train)

library(Amelia)
missmap(d.train, main = "Missing values vs observed")

head(d.train)
# Highly skewed on children count
hist(d.train$Children.count)

# Variable cleaning 
cvar <- colnames(d.input)[which(lapply(d.input,is.numeric)==F)]
d.input <- d.train %>%
  mutate(Has.children = ifelse(Children.count==0,"N","Y")) %>%
  mutate(across(cvar,as.factor)) %>%
  mutate(across(c("Has.a.mobile.phone","Has.a.work.phone","Has.a.phone","Has.an.email","Is.high.risk"),as.factor))

d.tt <- d.test %>%
  mutate(Has.children = ifelse(Children.count==0,"N","Y")) %>%
  mutate(across(cvar,as.factor)) %>%
  mutate(across(c("Has.a.mobile.phone","Has.a.work.phone","Has.a.phone","Has.an.email","Is.high.risk"),as.factor))


# Check Dummy
contrasts(d.input$Gender)

# Check Column all same value

# Modeling
lr.md <- glm(Is.high.risk ~ Gender + Has.a.car + Has.a.property + Income + Employment.status + Marital.status + Dwelling + Age + 
               Employment.length + Family.member.count + Account.age + Has.children,data=d.input, family = binomial(link = 'logit'))
summary(lr.md)
lr.md$coefficients


lr.md <- glm(Is.high.risk ~+ Income ,data=d.input, family = binomial(link = 'logit'))


# strong association of gender, have a property, marital status, employee length, account age with the probability of high risk
# In logit model, the response variable is log odds: 
# ln(odds) = ln(p/(1-p)) = a*x1 + b*x2 + … + z*xn. 
# Estimation of GenderM is 0.36 which means male have higher chance to be a high risk person than female. With p-value < 0.05, male and female have significant difference.
# Marital.status use "Civil marriage" as reference group. The chance of being high risk person who is Single or Widow are significant different from the reference group.
# ! Relevel multi-categorical variable can get different result. Depends on what you want to compare with.
# ! Re-categorize can get different result 

# Null deviance = SSTot
# Residual deviance = SSResid

anova(lr.md , test="Chisq")

confint(lr.md) # CI using profiled log-likelihood
confint.default(lr.md) # CI using standard errors 

# Prediction
fitted.results <- predict(lr.md ,newdata=d.tt,type='response')
fitted.results <- ifelse(fitted.results > 0.5,1,0)
table(fitted.results)
table(d.tt$Is.high.risk)
misClasificError <- mean(fitted.results != d.tt$Is.high.risk)
print(paste('Accuracy',1-misClasificError)) 

# Run k-fold cross validation can track the consistency of model accuracy.


# Print distribution of prediction --> want to know is it look like sigmoid function
pred <- predict(lr.md ,newdata=d.tt,type='response')
d.dist <- cbind.data.frame(d.tt$Is.high.risk,pred)
d.dist %>% 
  arrange(pred) %>%
  remove_rownames() %>%
  rowid_to_column() %>%
  ggplot(aes(x = rowid, y = pred)) +
  geom_point() + 
  labs(title = "Distribution of prediction", 
       subtitle = "output probability of logistic regression follow sigmoid function (S shaped)",
       y = "Prediction (probability)", x ="Row ID") + 
  theme_bw()




# ROC curve - binary classifier performance measurements
# The ROC is a curve generated by plotting the true positive rate (TPR) against the false positive rate (FPR) 
# a model with good predictive ability should have an area under ROC curve (AUC) closer to 1 (1 is ideal) than to 0.5.


